### ISSUE TITLE
tumour-normal paired

### ISSUE THREAD

**Issue by mtinti** [KCCG/ClinSV#5]
Hi, thanks for the package!
In the description paragraph is reported that ClinSV was used "to analyse somatic SV from tumour-normal paired WGS".  Can you please provide an example of the command line used in such case?

**Comment by drmjc** [comment]
I'm replying from my phone, so I can't type the command. Essentually you'll need to specify the two bams and create a Ped file where the germline is a parent, and the tumour is the child.

We don't use ClinSV for our cancer wgs pipeline, in part because it doesn't use BAF, so I recommend you look into purple and gridss2 for somatic cnv and SV calling though, from our collaborators at Hartwig Medical Foundation and Peter Mac in Melbourne. The merits of this approach are outlined in our recent paper https://pubmed.ncbi.nlm.nih.gov/33020650/

Cheers, Mark
________________________________
From: mtinti ***@***.***>
Sent: Tuesday, June 8, 2021 8:04:48 PM
To: KCCG/ClinSV ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KCCG/ClinSV] tumour-normal paired (#5)


Hi, thanks for the package!
In the description paragraph is reported that ClinSV was used "to analyse somatic SV from tumour-normal paired WGS". Can you please provide an example of the command line used in such case?

**Comment by mtinti** [comment]
Thanks, I will try ClinSV and look into purple as suggested .
cheers
Michele
